.TH emission 1 17-FEB-2023 "Kozmix Go"

.SH NAME
emission \- do calculations on measurements from the author's valve tester

.SH SYNOPSIS
.B emission
<valve type> ht=... curr=... [nb=...]

.SH DESCRIPTION
.B emission
processes the test results from the author's valve tester. The command
line arguments are:

.TP
.B designation
The valve type (EL84, ECC83, etc; case-insensitive).
.TP
.B ht=...
HT (anode) voltage as measured from the red socket, in volts. This
will be around 150V for preamp valves and around 300V for power
valves.
.TP
.B curr=...
Cathode current as measured from the green socket (where 1mV measured equals 1mA).
.TP
.B nb=...
Negative bias voltage as measured from the blue socket and set with
the knob to the left of it (optional).

.P
.B emission
will then calculate power dissipation, and emit warnings if any
measured values exceed maximum values (or in case of negative bias,
are more than 10% off the recommended testing value).

.SH EXAMPLES

.EX
$ emission pwr el84 curr=48m ht=297 nb=14
valve: EL84 (power valve)

value                     measured   nominal/max.
anode voltage        V =      297V      300V
negative bias        V =      -14V      -14V
cathode current      I =      48mA      65mA
dissipation          P =   14.256W       12W  WARNING

.EE


.SH SEE ALSO
.BR valve (1)

.SH BUGS
.B emission
only has data on a limited range of valve types built in, and only
knows them by their Philips/Mullard designations.

.SH AUTHOR
svm

